
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author hp
 */
public class marksadd extends javax.swing.JFrame {

    /**
     * Creates new form marksadd
     */
    public marksadd() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar1 = new javax.swing.JScrollBar();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jToggleButton2 = new javax.swing.JToggleButton();
        jLabel2 = new javax.swing.JLabel();
        t8 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        c3 = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        c4 = new javax.swing.JComboBox();
        t14 = new javax.swing.JTextField();
        t9 = new javax.swing.JTextField();
        t15 = new javax.swing.JTextField();
        t10 = new javax.swing.JTextField();
        t16 = new javax.swing.JTextField();
        t11 = new javax.swing.JTextField();
        t17 = new javax.swing.JTextField();
        t12 = new javax.swing.JTextField();
        t18 = new javax.swing.JTextField();
        t13 = new javax.swing.JTextField();
        jToggleButton3 = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 102, 255));

        jPanel2.setBackground(new java.awt.Color(255, 102, 0));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("    ADD CT MARKS");

        jToggleButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jToggleButton2.setText("BACK");
        jToggleButton2.setBorder(null);
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jToggleButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addComponent(jLabel1)
                .addContainerGap(211, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jToggleButton2)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("ROLL NO.");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("BRANCH");

        c3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "cse", "it", "mech", "civil", "EEE" }));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("SEM");

        c4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6" }));
        c4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c4ActionPerformed(evt);
            }
        });

        t9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t9ActionPerformed(evt);
            }
        });

        t15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t15ActionPerformed(evt);
            }
        });

        t12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t12ActionPerformed(evt);
            }
        });

        t18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t18ActionPerformed(evt);
            }
        });

        jToggleButton3.setBackground(new java.awt.Color(255, 51, 0));
        jToggleButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jToggleButton3.setText("SAVE");
        jToggleButton3.setBorder(null);
        jToggleButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(t14, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(t15, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                        .addComponent(t18)
                        .addComponent(t17)
                        .addComponent(t16, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(t9, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(t12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                            .addComponent(t8, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(c3, javax.swing.GroupLayout.Alignment.LEADING, 0, 116, Short.MAX_VALUE)
                            .addComponent(c4, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(t13, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(t11, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(t10, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jToggleButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(c3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(c4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(t15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(t10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
this.setVisible(false);
menu m=new menu();
m.setVisible( true);        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void t9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t9ActionPerformed

    private void t18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t18ActionPerformed

    private void jToggleButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton3ActionPerformed
try{
       Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/javactproject","root",""); 
            Statement stmt=con.createStatement();// TODO add your handling code here:
            int mark1=Integer.parseInt(t9.getText());
              int mark2=Integer.parseInt(t10.getText());
              int mark3=Integer.parseInt(t11.getText());
              int mark4=Integer.parseInt(t12.getText());
              int mark5=Integer.parseInt(t13.getText());
              int totalmarks=mark1+mark2+mark3+mark4+mark5;
              float percent=(totalmarks*100)/400;
              int rollnum=Integer.parseInt(t8.getText());
              String branch=c3.getSelectedItem().toString();
              int sem=Integer.parseInt(c4.getSelectedItem().toString());
              
   
             String q="insert into report values('"+rollnum+"','"+branch+"','"+sem+"','"+mark1+"','"+mark2+"','"+mark3+"','"+mark4+"','"+mark5+"','"+totalmarks+"','"+percent+"')";
             
            int rs=stmt.executeUpdate(q);
            
            if(rs!=0){
                JOptionPane.showMessageDialog(null,"marks Added Succesfully");
                t9.setText("");
                t10.setText("");
                t11.setText("");
                t12.setText("");
                t13.setText("");
                t8.setText("");
                
            }
               
            
            else{
                JOptionPane.showMessageDialog(null,"Error");
            }
               con.close();
    }
catch(Exception ex){ 
    System.out.println(ex);
}        // TODO add your handling code here:        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton3ActionPerformed

    private void c4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c4ActionPerformed

String selectedbranch=c3.getSelectedItem().toString();
int sem=Integer.parseInt(c4.getSelectedItem().toString());
if((selectedbranch.equals("cse"))&&(sem==1)){
t14.setText("physics");
t15.setText("m1");
t16.setText("Fme");
t17.setText("Eco");
t18.setText("civil");
}
else if((selectedbranch.equals("cse"))&&(sem==2)){
t14.setText("chemistry");
t15.setText("m2");
t16.setText("EEE");
t17.setText("English");
t18.setText("ED");
}
else if((selectedbranch.equals("cse"))&&(sem==3)){
t14.setText("BE");
t15.setText("m3");
t16.setText("C");
t17.setText("CS");
t18.setText("DELD");
}
else if((selectedbranch.equals("cse"))&&(sem==4)){
t14.setText("CSA");
t15.setText("Discreate maths");
t16.setText("Computation maths");
t17.setText("Data Structure");
t18.setText("c++");
}

else if((selectedbranch.equals("cse"))&&(sem==5)){
t14.setText("Micro");
t15.setText("Ada");
t16.setText("java");
t17.setText("dbms");
t18.setText("unix");
}
else if((selectedbranch.equals("cse"))&&(sem==6)){
t14.setText("Computer Networks");
t15.setText("Compiler Design");
t16.setText("Resource Planning");
t17.setText("Graphics");
t18.setText("project management");
}
else if((selectedbranch.equals("it"))&&(sem==1)){
t14.setText("physics");
t15.setText("calculus");
t16.setText("solids");
t17.setText("English");
t18.setText("ED");
}
else if((selectedbranch.equals("it"))&&(sem==2)){
t14.setText("chemistry");
t15.setText("linear algebra");
t16.setText("Eco");
t17.setText("programming");
t18.setText("EEE");
}
else if((selectedbranch.equals("it"))&&(sem==3)){
t14.setText("BE");
t15.setText("Applied maths");
t16.setText("OOPS");
t17.setText("Security");
t18.setText("DELD");
}
else if((selectedbranch.equals("it"))&&(sem==4)){
t14.setText("CSA");
t15.setText("maths");
t16.setText("Communication");
t17.setText("Data Structure");
t18.setText("economics");
}

else if((selectedbranch.equals("it"))&&(sem==5)){
t14.setText("toc");
t15.setText("Ada");
t16.setText("datacommunication");
t17.setText("dbms");
t18.setText("OS");
}
else if((selectedbranch.equals("it"))&&(sem==6)){
t14.setText(".net");
t15.setText("java");
t16.setText("C");
t17.setText("Lamp");
t18.setText("project management");
}
else if((selectedbranch.equals("mech"))&&(sem==1)){
t14.setText("calculus");
t15.setText("chemistry");
t16.setText("EEE");
t17.setText("Eco");
t18.setText("programming");
}
else if((selectedbranch.equals("mech"))&&(sem==2)){
t14.setText("algebra");
t15.setText("physics");
t16.setText("solids");
t17.setText("English");
t18.setText("ED");
}
else if((selectedbranch.equals("mech"))&&(sem==3)){
t14.setText("kinematics");
t15.setText("thermodynamics");
t16.setText("manufacturing");
t17.setText("economics");
t18.setText("materials");
}
else if((selectedbranch.equals("mech"))&&(sem==4)){
t14.setText("dynamics");
t15.setText("metrology");
t16.setText("maths");
t17.setText("fluid");
t18.setText("security");
}

else if((selectedbranch.equals("mech"))&&(sem==5)){
t14.setText("dynamics");
t15.setText("powerplant");
t16.setText("fluidpower");
t17.setText("heat");
t18.setText("controlengg.");
}
else if((selectedbranch.equals("mech"))&&(sem==6)){
t14.setText("production");
t15.setText("design");
t16.setText("thermal");
t17.setText("laws");
t18.setText("OOPS");
}
else if((selectedbranch.equals("civil"))&&(sem==1)){
t14.setText("calculus");
t15.setText("chemistry");
t16.setText("programming");
t17.setText("Eco");
t18.setText("civil");
}
else if((selectedbranch.equals("civil"))&&(sem==2)){
t14.setText("algebra");
t15.setText("physics");
t16.setText("solids");
t17.setText("English");
t18.setText("ED");
}
else if((selectedbranch.equals("civil"))&&(sem==3)){
t14.setText("Building");
t15.setText("m3");
t16.setText("surveying");
t17.setText("planning");
t18.setText("economics");
}
else if((selectedbranch.equals("civil"))&&(sem==4)){
t14.setText("geology");
t15.setText("mechanics");
t16.setText("Construction");
t17.setText("fluid");
t18.setText("security");
}

else if((selectedbranch.equals("civil"))&&(sem==5)){
t14.setText("design");
t15.setText("resources");
t16.setText("eco");
t17.setText("transpotation");
t18.setText("foundation");
}
else if((selectedbranch.equals("civil"))&&(sem==6)){
t14.setText("structures");
t15.setText("ecc");
t16.setText("Resource Planning");
t17.setText("laws");
t18.setText("project management");
}
else if((selectedbranch.equals("EEE"))&&(sem==1)){
t14.setText("physics");
t15.setText("m1");
t16.setText("Fme");
t17.setText("Eco");
t18.setText("civil");
}
else if((selectedbranch.equals("EEE"))&&(sem==2)){
t14.setText("chemistry");
t15.setText("m2");
t16.setText("EEE");
t17.setText("English");
t18.setText("ED");
}
else if((selectedbranch.equals("EEE"))&&(sem==3)){
t14.setText("thermal");
t15.setText("m3");
t16.setText("Analog");
t17.setText("network");
t18.setText("transducer");
}
else if((selectedbranch.equals("EEE"))&&(sem==4)){
t14.setText("fundamentals");
t15.setText("machine");
t16.setText("power");
t17.setText("controlsystem");
t18.setText("economics");
}

else if((selectedbranch.equals("EEE"))&&(sem==5)){
t14.setText("analysis");
t15.setText("electronics");
t16.setText("high voltage");
t17.setText("micro");
t18.setText("power");
}
else if((selectedbranch.equals("EEE"))&&(sem==6)){
t14.setText("power system");
t15.setText("electrical");
t16.setText("testing");
t17.setText("energy");
t18.setText("adv micro");
}        // TODO add your handling code here:
    }//GEN-LAST:event_c4ActionPerformed

    private void t12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t12ActionPerformed

    private void t15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t15ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(marksadd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(marksadd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(marksadd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(marksadd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new marksadd().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox c3;
    private javax.swing.JComboBox c4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JTextField t10;
    private javax.swing.JTextField t11;
    private javax.swing.JTextField t12;
    private javax.swing.JTextField t13;
    private javax.swing.JTextField t14;
    private javax.swing.JTextField t15;
    private javax.swing.JTextField t16;
    private javax.swing.JTextField t17;
    private javax.swing.JTextField t18;
    private javax.swing.JTextField t8;
    private javax.swing.JTextField t9;
    // End of variables declaration//GEN-END:variables
}
