/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.io.OutputStreamWriter;
import java.net.URL;
import java.net.URLConnection;
import java.net.URLEncoder;
/**
 *
 * @author hp
 */
public class menu extends javax.swing.JFrame {

    /**
     * Creates new form menu
     */
    public menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        m1 = new javax.swing.JMenu();
        mi1 = new javax.swing.JMenuItem();
        mi2 = new javax.swing.JMenuItem();
        m2 = new javax.swing.JMenu();
        mi4 = new javax.swing.JMenuItem();
        mi5 = new javax.swing.JMenuItem();
        mi6 = new javax.swing.JMenuItem();
        m3 = new javax.swing.JMenu();
        mi7 = new javax.swing.JMenuItem();
        mi8 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\hp\\Downloads\\finalcsvtu.jpeg")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 648, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        m1.setText("Student");

        mi1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        mi1.setText("Add");
        mi1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi1ActionPerformed(evt);
            }
        });
        m1.add(mi1);

        mi2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        mi2.setText("Show");
        mi2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi2ActionPerformed(evt);
            }
        });
        m1.add(mi2);

        jMenuBar1.add(m1);

        m2.setText("CT");

        mi4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        mi4.setText("Add");
        mi4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi4ActionPerformed(evt);
            }
        });
        m2.add(mi4);

        mi5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        mi5.setText("Show");
        mi5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi5ActionPerformed(evt);
            }
        });
        m2.add(mi5);

        mi6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        mi6.setText("Report");
        mi6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi6ActionPerformed(evt);
            }
        });
        m2.add(mi6);

        jMenuBar1.add(m2);

        m3.setText("SMS");

        mi7.setText("One");
        mi7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi7ActionPerformed(evt);
            }
        });
        m3.add(mi7);

        mi8.setText("Bulk");
        mi8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi8ActionPerformed(evt);
            }
        });
        m3.add(mi8);

        jMenuBar1.add(m3);

        jMenu1.setText("LogOut");

        jMenuItem1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenuItem1.setText("SignOut");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mi7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi7ActionPerformed
this.setVisible(false);
sms s=new sms();
s.setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_mi7ActionPerformed

    private void mi1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi1ActionPerformed
this.setVisible(false);
Studentdetails std=new Studentdetails();
std.setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_mi1ActionPerformed

    private void mi2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi2ActionPerformed
this.setVisible(false);
searchstudent std=new searchstudent();
std.setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_mi2ActionPerformed

    private void mi4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi4ActionPerformed
this.setVisible(false);
marksadd madd=new marksadd();
madd.setVisible(true);

// TODO add your handling code here:
    }//GEN-LAST:event_mi4ActionPerformed

    private void mi5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi5ActionPerformed
this.setVisible(false);
searchctmarks ct=new searchctmarks();
ct.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_mi5ActionPerformed

    private void mi8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi8ActionPerformed
this.setVisible(false);
bulksms bs=new bulksms();
bs.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_mi8ActionPerformed

    private void mi6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi6ActionPerformed
reportframe rf=new reportframe();
this.setVisible(false);
rf.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_mi6ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu m1;
    private javax.swing.JMenu m2;
    private javax.swing.JMenu m3;
    private javax.swing.JMenuItem mi1;
    private javax.swing.JMenuItem mi2;
    private javax.swing.JMenuItem mi4;
    private javax.swing.JMenuItem mi5;
    private javax.swing.JMenuItem mi6;
    private javax.swing.JMenuItem mi7;
    private javax.swing.JMenuItem mi8;
    // End of variables declaration//GEN-END:variables
}
